ports:
- port: 8000
  onOpen: open-preview
tasks:
  - init: composer install
    command: >
      cp .env.example .env;
      php artisan key:generate;
      docker-compose up -d;
      php artisan migrate;
      php artisan serve